### ISSUE TITLE
Other useful metrics

### ISSUE THREAD

**Issue by diodon** [sprouffske/growthcurver#4]
Hi, nice simple package.

I cannot find any documentation related to the "other useful metrics" output from `SummarizeGrowth`. Specifically what are the mean of DT and 1/DT

**Comment by sprouffske** [comment]
Hi @diodon, 

Thanks for your question! 

DT is doubling time and 1/DT is the inverse of doubling time. The documentation for `SummarizeGrowth` could use some updating, so I'll include that in the next version. 

In the meantime, you can find the documentation for all the metrics from within R by looking at growthcurver's associated help. You can load growthcurver and then find the help from the R prompt by typing

```
library(growthcurver)
?gcvals
```

Please let me know if this doesn't answer your question.
