### ISSUE TITLE
Simple fix in vignette

### ISSUE THREAD

**Issue by kdzimm** [sprouffske/growthcurver#6]
@sprouffske,

Thanks for the great package. Very helpful resource. I just wanted to make one note. It is a simple fix.

In your vignette here:
https://cran.r-project.org/web/packages/growthcurver/vignettes/Growthcurver-vignette.html#quality-control-and-best-practices

You say that the sigma value is the "measure of the goodnesss of fit of the parameters of the logistic equation for the data; it is the residual sum of squares from the nonlinear regression model." So I went ahead and was using that value as if it were the RSS, but something seemed a bit off. When I looked, it appeared to be a residual standard error. Sure enough, when I checked the reference manual it says the sigma is the RSE. If you wanted to fix that in your vignette, it would be much appreciated. 

Thanks again!

**Comment by sprouffske** [comment]
Thanks for catching this! I updated the documentation in the latest release.
