### ISSUE TITLE
How can I get the value of lag time?

### ISSUE THREAD

**Issue by EugeneAeolus** [sprouffske/growthcurver#9]
Describe the bug:
Hi
I found in the paper that the lag time can be obtained through this package, but I just find values such as k, n0 and r
Is the lag time calculated by the population size at the beginning of the growth curve (N0)?

Reference: https://doi.org/10.1073/pnas.2103027118

Yours sincerely

**Comment by sprouffske** [comment]
As a proxy for lag time, consider using the time to the inflection point / midpoint (t_mid).
